{
 "title": "Instagram",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Comments count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "instagram_comments_count", "legendFormat": "{{ imageId }}" }
   ]
  },
  {
   "title": "Likes count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "instagram_likes_count", "legendFormat": "{{ imageId }}" }
   ]
  },
  {
   "title": "Likes increase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(instagram_likes_count[5m])",
     "legendFormat": "{{ imageId }}"
    }
   ]
  },
  {
   "title": "Likes count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "instagram_likes_count", "legendFormat": "{{ imageId }}" }
   ]
  },
  {
   "title": "Errors counter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "instagram_errors_count" }
   ]
  },
  {
   "title": "Likes increase 1h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(instagram_likes_count[1h])",
     "legendFormat": "{{ imageId }}"
    }
   ]
  },
  {
   "title": "Followers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "instagram_followers_count", "legendFormat": "{{ account }}" }
   ]
  }
 ]
}