name: image
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHR_TOKEN }}
          registry: ghcr.io
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/mariadb
          file: Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ghcr.io/aldor007/insti:latest, ghcr.io/aldor007/insti:${{ steps.vars.outputs.tag }}
          cache-from: type=registry,ref=ghcr.io/aldor007/insti:latest
          cache-to: type=inline